# Generated by Django 4.0.6 on 2022-07-24 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_menuitem_price_alter_menuitem_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='image',
        ),
    ]
